### ISSUE TITLE
create roles + message app in maintenance on homepage

### ISSUE THREAD

**Issue by Hiteazel** [GoofyComponent/RandomGraill#71]
## Issue opened at 15-09-2024 00:28:56 
[2024-09-14T22:28:56Z]

**Comment by Hiteazel** [comment]
Create role admin + message maintenance for user who are not admin

Hide "Nearby restaurant" on Homepage that not working at the moment

**Comment by DestroyCom** [comment]
DEUX JOURS ET DOUZE HEURES 🤯🤯🤯🤯🤯🤯
